name: Complete a publish dry-run
on: workflow_dispatch

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Complete a publish dry-run
        uses: icorbrey/publish-dart-package@v1
        with:
          credentials: ${{ secrets.CREDENTIAL_JSON }}
          publish_method: dry-run
