name: Publish to pub.dev

on:
  release:
    types: [published]

jobs:

  publish-to-registry:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Publish to pub.dev
        uses: icorbrey/publish-dart-package@v1
        with:
          credentials: ${{ secrets.CREDENTIAL_JSON }}
          publish_method: standard
